swagger: '2.0'
info:
  version: 2.0.0
  title: Endpoint parametrizado
  description: Endpoint parametrizado
paths: 
  /api/v1/users/:id:
    put:
      summary: Alterar único usuário
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: '#/definitions/body_request'
      responses:
        201:
          description: Usuário alterado com sucesso.
        404:
          description: Usuário não encontrado.
        500:
          description: Ocorreu um erro no servidor.
    delete:
      summary: deletar único usuário
      responses:
        204:
          description: Dados removidos com Sucesso.
        404:
          description: Usuário não encontrado.
        500:
          description: Ocorreu um erro no servidor.
    get:
      summary: Listar único usuário
      responses:
        200:
          description: OK.
          schema:
            $ref: '#/definitions/body_response'
        404:
          description: Usuário não encontrado.
        500:
          description: Ocorreu um erro no servidor.
definitions:
  body_request:
    type: object
    required:
      - email
      - senha
    properties:
      email:
        type: string
        example: Thomas@gmail.com
        format: email
      senha:
        type: string
        example: 1234
        format: password
  body_response:
    type: object
    required:
      - id
      - email
      - senha
    properties:
      id:
        type: string
        example: 14504
        format: string
      email:
        type: string
        example: Thomas@gmail.com
        format: email
      senha:
        type: string
        example: 1234
        format: string